loadState();
renderHomeIcons();
renderTodayIcons()
renderCalendarIcons()
renderHabits();
renderMood();
renderEnergy();
renderGeneralSection();
renderMenstrualSection();
renderHomeScreen();
setupHabitsStatusHealthSwipe();
attachDayViewSwipeListener();
showScreen("home-screen");
