loadState();
checkChecklistResets();
renderHomeIcons();
renderTodayIcons()
renderCalendarIcons()
renderHabits();
renderMood();
renderEnergy();
renderGeneralSection();
renderPeriodSection();
renderMenstrualSection();
renderWeeklyChecklist();
renderMonthlyChecklist();
renderProjectsChecklist();
renderHomeScreen();
setupHabitsStatusHealthSwipe();
setupChecklistSwipe();
attachDayViewSwipeListener();
attachGridSwipeListener();
attachTrackerSwipeListener();
attachInsightsSwipeListener();
maybeAutoBackup();
showScreen("home-screen");
